// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sprint-card/VariantA.tsx": () => import("../components/mockups/sprint-card/VariantA.tsx"),
  "./components/mockups/sprint-card/VariantB.tsx": () => import("../components/mockups/sprint-card/VariantB.tsx"),
  "./components/mockups/sprint-card/VariantC.tsx": () => import("../components/mockups/sprint-card/VariantC.tsx")
};
